version: 2
jobs:
  build:
    # directory where steps are run
    working_directory: ~/apk_bitminer
    docker:
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
        environment:
          PYTHONASYNCIODEBUG: 1
          PYTHONPATH: ../src:.
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: setup python venv
          command: |
            /usr/local/bin/python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd apk_bitminer/test
            pytest . --cov=../src --cov-report html:test-reports/coverage --html test-reports/resport.html
      - store_artifacts:
          path: apk_bitminer/test/test-reports/
          destination: python_app
